### ISSUE TITLE
[BUG]resume和main之间的一段时间可能会错过一些so

### ISSUE THREAD

**Issue by LLeavesG** [SeeFlowerX/frida_dump#3]
存在的问题：在实际测试中会发现无法找到某些so，查看dlopen的时机可以发现第一条log之前就已经加载了一些内容，其中包括base.odex，原因出在resume和main rpc调用之间的时间并未进行hook

`Existing problems: in the actual test will find that can not find some so, check the timing of the dlopen can be found before the first log has been loaded some of the content, including base.odex, the reason for this is that the time between the resume and main rpc call is not hooked`

建议的改动：
修改前(Before)
```
            session = device.attach(pid)
            device.resume(pid)
        else:
            logger.info(f'start attach {target}')
            
            session = device.attach(target)

    except Exception as e:
        logger.error(f'attach to {target} failed', exc_info=e)
        sys.exit()

    logger.info(f'attach {target} success, inject script now')
    try:
        jscode = Path('frida_dump/dump_so.js').read_text(encoding='utf-8')
        script = session.create_script(jscode, runtime='qjs')
        script.load()
        session.on('detached', on_detached)
        base_name = os.path.splitext(args.TARGET[0])[0]
        script.on('message', lambda message, data: on_message(message, data, base_name, args.sofixer))
    except Exception as e:
        logger.error(f'inject script failed', exc_info=e)
        sys.exit()
    rpc = script.exports
    if args.spawn:
        rpc.main(args.TARGET[0])
```
修改后(After)
```
        device.resume(pid)
        rpc.main(args.TARGET[0])
```

**Comment by LLeavesG** [comment]
Example:
腾讯游戏安全竞赛2023Android初赛赛题
https://gslab.qq.com/html/competition/2023/doc/%E5%AE%89%E5%8D%93%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%AE%89%E5%85%A8-%E5%88%9D%E8%B5%9B%E9%A2%98%E7%9B%AE.zip
TARGET libsec2023.app

**Comment by SeeFlowerX** [comment]
感谢反馈，已修复
